apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: iot-messages
  namespace: kafka
  labels:
    strimzi.io/cluster: iot-cluster
spec:
  partitions: 6
  replicas: 1
  config:
    retention.ms: "259200000"
    compression.type: "snappy"
    min.insync.replicas: "1"
    segment.ms: "3600000"
    cleanup.policy: "delete"
